var preguntas = [
    "¿Cuántos capítulos tiene Pasión de Gavilanes?",
    "¿Cuántas sagas tiene el conjuro?",
    "¿Cuántas temporadas tiene The Walking Dead?",
    "¿Cuántos capítulos tiene El Juego del Calamar?",
    "¿Qué género es la película De todos los chicos que me enamoré?",
    "¿Qué drama es la serie Love Alarm?",
    "¿En qué año fue creada la película El Aro?",
    "¿Cuántas temporadas tiene la serie Naruto?",
    "¿Qué género crees que es la nueva serie de Chucky?",
    "¿Cuántas temporadas tiene la serie You?",
    "¿Quién es la protagonista de la pelicula Aves de presa?",
    "¿Cuántas películas contiene la saga Los Vengadores?",
    "La película Buscando a Dory, ¿a qué género pertenece?",
    "Indica que te parece la serie Elite",]
var opciones = [
    ["100 Capítulos",
"150 Capítulos",
"188 Capítulos",
"200 Capítulos"],
["1 Saga",
"2 Sagas", 
"3 Sagas",
"4 Sagas"],
["2 Temporadas",
"5 Temporadas",
"11 Temporadas",
"17 Temporadas"],
["3 Capítulos",
"7 Capítulos",
"9 Capítulos",
"13 Capítulos"],
["Romántica",
"Comedia",
"Terror",
"Acción"],
["Romántica",
"Acción",
"Suspenso",
"Drama"],
["1995",
"2002",
"2006",
"2013"]]
